// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      // Language Model preferences
      "modelType": string;
      "apiKey": string;
      
      // Relevance Thresholds
      "thresholdHigh": number;
      "thresholdMedium": number;
      "thresholdLow": number;
      
      // Performance Settings
      "dbLocation": string;
      "cacheSize": number;
      "autoCleanup": boolean;
      
      // Base preferences
      "enable": boolean;
      "input": string;
    };
  }
}
